'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Check,ChevronDown,ChevronRight,Copy,FileText,Flag,Info,Layers,LoaderCircle,MapPin,Search,ShieldCheck,X} from 'lucide-react';
import {ProposalSchema,type Proposal,type AnalysisResult,type Finding,type SourceRecord} from '@/lib/schemas';
import type {Comparison} from '@/lib/analysis/engine';
const ParcelMap=dynamic(()=>import('./parcel-map'),{ssr:false,loading:()=> <div className="map-section map-loading">Loading parcel map…</div>});
const initial:Proposal={scope:'new_construction',buildingType:'small_multifamily',units:3,stories:2,footprintSqFt:1400,heightFt:28};
const labels:Record<string,string>={pass:'Assessed',concern:'Review',major:'Major concern',apparent_conflict:'Apparent conflict',unknown:'Verification required',not_applicable:'Not applicable'};
const fieldNames:Record<string,string>={units:'unit count',buildingType:'building type',scope:'project scope',stories:'stories',heightFt:'height',footprintSqFt:'footprint area'};
function SourceLink({source}:{source:SourceRecord}){return <div className="source-record"><a href={source.queryUrl??source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={16}/></a><small>{source.mode} · retrieved {new Date(source.retrievedAt).toLocaleString()}{source.error&&` · ${source.error}`}</small></div>;}
function Evidence({finding,sources,onClose}:{finding:Finding,sources:SourceRecord[],onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();const el=ref.current;return()=>el?.close();},[]);
 return <dialog ref={ref} className="evidence-drawer" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="drawer-content"><div className="section-heading"><span className="eyebrow">THE EVIDENCE</span><button className="icon-button" onClick={onClose} aria-label="Close evidence"><X/></button></div><h2>{finding.title}</h2><span className={`badge ${finding.status}`}>{labels[finding.status]}</span><p>{finding.summary}</p><dl>{finding.measuredValue!==undefined&&<><dt>Measured / evaluated</dt><dd>{finding.measuredValue} {finding.units}</dd></>}{finding.calculation&&<><dt>Method</dt><dd>{finding.calculation}</dd></>}{finding.ruleId&&<><dt>Rule version</dt><dd>{finding.ruleId}</dd></>}<dt>Score deduction</dt><dd>{finding.penalty} points</dd><dt>Limits of this check</dt><dd>{finding.limitation}</dd><dt>Verify next</dt><dd>{finding.nextStep}</dd></dl><h3>Source records</h3>{sources.filter(s=>finding.sourceIds.includes(s.id)).map(s=><SourceLink key={s.id} source={s}/>)}</div></dialog>;
}
function ProposalForm({proposal,onChange}:{proposal:Proposal,onChange:(p:Proposal)=>void}){
 return <div className="proposal-grid"><label className="wide">Project scope<select value={proposal.scope} onChange={e=>onChange({...proposal,scope:e.target.value as Proposal['scope']})}><option value="new_construction">New construction</option><option value="addition">Addition</option><option value="renovation">Renovation</option></select></label><label className="wide">Residential building type<select value={proposal.buildingType} onChange={e=>{const buildingType=e.target.value as Proposal['buildingType'];onChange({...proposal,buildingType,units:buildingType==='detached'?1:buildingType==='two_unit'?2:Math.max(3,proposal.units)});}}><option value="detached">Single-unit detached</option><option value="two_unit">Two-unit residential</option><option value="small_multifamily">Small multifamily</option></select></label>{([['units','Housing units',24],['stories','Stories',12],['heightFt','Approx. height (ft)',200],['footprintSqFt','Approx. footprint (sq ft)',100000]] as const).map(([key,label,max])=><label key={key}>{label}<input type="number" min={key==='heightFt'||key==='footprintSqFt'?0.1:1} max={max} step={key==='heightFt'||key==='footprintSqFt'?'any':1} required={key==='units'||key==='stories'} value={proposal[key]??''} onChange={e=>onChange({...proposal,[key]:e.target.value===''?undefined:Number(e.target.value)})}/></label>)}</div>;
}
function Score({result,name}:{result:AnalysisResult,name?:string}){const s=result.score;return <div className="score-summary"><div><span className="eyebrow">{name??'DEVELOPMENT EASE'}</span><h3>{s.value===null?'Score unavailable':s.label==='fewer_identified_constraints'?'Fewer identified constraints':s.label==='additional_review_likely'?'Additional review likely':'Major identified constraint'}</h3><p>{s.value===null?'Critical checks need verification.':'Provisional summary of implemented checks only.'}</p><span className="coverage"><ShieldCheck size={15}/>{s.assessedChecks} of {s.eligibleChecks} checks assessed</span></div><div className={`score-number ${s.value===null?'unknown':s.value<50?'conflict':''}`}>{s.value??'—'}<span>{s.value===null?'UNAVAILABLE':'/ 100'}</span></div></div>;}
export default function Workspace({initialResult}:{initialResult:AnalysisResult|null}){
 const [pin,setPin]=useState(initialResult?.parcel.pin??'0083A00188000000');const [result,setResult]=useState(initialResult);
 const [a,setA]=useState<Proposal>(initial),[b,setB]=useState<Proposal>({...initial,units:4});
 const [tab,setTab]=useState<'report'|'compare'|'sources'>('report'),[active,setActive]=useState<'A'|'B'>('A');
 const [comparison,setComparison]=useState<Comparison|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[evidence,setEvidence]=useState<Finding|null>(null);
 const [showForm,setShowForm]=useState(true);
 async function run(selectedPin=pin,mode:'report'|'compare'='report',refresh=false){
 const valid=ProposalSchema.safeParse(a),validB=ProposalSchema.safeParse(b);if(!valid.success||mode==='compare'&&!validB.success){setError((!valid.success?valid.error:!validB.success?validB.error:null)?.issues.map(i=>i.message).join(' ')??'Check proposal inputs.');return;}
 setBusy(true);setError('');try{const response=await fetch(`/api/${mode==='compare'?'compare':'analyze'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='compare'?{pin:selectedPin,scenarioA:a,scenarioB:b}:{pin:selectedPin,proposal:a,refresh})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(mode==='compare'){setComparison(data);setResult(data.a);}else{setResult(data);setComparison(null);}setPin(data.parcel?.pin??data.a.parcel.pin);setDirty(false);const url=new URL(window.location.href);url.searchParams.set('pin',data.parcel?.pin??data.a.parcel.pin);window.history.replaceState(null,'',url);setTab(mode);if(mode==='report')setActive('A');}catch(e){setError(e instanceof Error?e.message:'Unable to load parcel.');}finally{setBusy(false);}}
 const display=tab==='compare'&&active==='B'&&comparison?comparison.b:result;
 const change=(p:Proposal)=>{if(active==='A')setA(p);else setB(p);setDirty(true);};
 const issues=display?.findings.filter(f=>f.status==='major'||f.status==='apparent_conflict'||f.status==='unknown')??[];
 return <><header className="app-header"><Link className="brand" href="/" aria-label="ParcelPilot home"><span className="brand-mark"><Layers size={23}/></span>Parcel<span>Pilot</span></Link><div className="header-divider"/><span className="header-caption">Housing development, thoughtfully screened.</span><span className="city-pill"><MapPin size={14}/>Pittsburgh, PA</span><span className="prototype">RESEARCH PREVIEW</span></header>
 <main><div className="workspace-title"><div><div className="eyebrow">PARCEL WORKSPACE</div><h1>See the site. Explore the possibilities.</h1><p>Screen a housing proposal, understand the evidence, and compare what changes.</p></div><a className="text-link mobile-map-link" href="#parcel-map">View map <ArrowRight size={16}/></a></div>
 <section className="search-strip"><form onSubmit={e=>{e.preventDefault();void run();}}><label htmlFor="pin">Find a parcel</label><div className="search-field"><Search size={18}/><input id="pin" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Enter official parcel PIN" maxLength={24}/><button disabled={busy} type="submit" aria-label="Find parcel">{busy?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>}</button></div></form><div className="sample-parcels"><span>TRY A REAL PARCEL</span><button disabled={busy} onClick={()=>void run('0083A00188000000')}>83-A-188 <ArrowUpRight size={14}/></button><button disabled={busy} onClick={()=>void run('0083A00248000000')}>83-A-248 <ArrowUpRight size={14}/></button></div><div className="coverage-note"><ShieldCheck size={17}/><span>City of Pittsburgh coverage<br/><small>Official public GIS sources</small></span></div></section>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 <div className="workspace-grid"><aside className="site-column">{result?<><ParcelMap parcel={result.parcel}/><section className="parcel-card"><div className="section-heading"><span className="eyebrow">SELECTED PARCEL</span><span className="badge neutral">{result.parcel.sources.some(s=>s.mode==='snapshot')?'Dated public snapshot':result.parcel.sources.some(s=>s.mode==='cached')?'Cached public data':'Live public data'}</span></div><h2><MapPin size={20}/>{result.parcel.pin}</h2><div className="parcel-stats"><div><span>Parcel area</span><strong>{Math.round(result.parcel.reportedAreaSqFt).toLocaleString()} <small>sq ft</small></strong></div><div><span>Mapped district</span><strong>{result.parcel.zoningDistricts.map(d=>d.code).join(' / ')||'Unknown'}</strong></div><div><span>Municipality</span><strong>Pittsburgh</strong></div></div><p className="data-date">Retrieved {new Date(result.parcel.sources[0].retrievedAt).toLocaleString()} <button disabled={busy} onClick={()=>void run(result.parcel.pin,'report',true)}>Refresh sources</button></p></section><div className="map-note"><Info size={17}/><p>A parcel boundary is a starting point. The map does not show where your proposed building would sit.</p></div></>:<div className="empty-state"><MapPin size={40}/><h2>Select a Pittsburgh parcel</h2><p>Enter its official PIN or choose a real sample to begin.</p></div>}</aside>
 <div className="analysis-column"><nav className="workspace-tabs" aria-label="Workspace views">{([['report','Proposal & findings'],['compare','Compare scenarios'],['sources','Sources']] as const).map(([id,title])=><button key={id} className={tab===id?'selected':''} onClick={()=>{setTab(id);if(id==='report')setActive('A');}}>{title}{id==='compare'&&<span>A/B</span>}</button>)}</nav>
 {tab!=='sources'&&<section className="proposal-card"><button className="proposal-heading" onClick={()=>setShowForm(!showForm)} aria-expanded={showForm}><div><span className="step-number">01</span><h2>Your proposal</h2></div><ChevronDown size={18} className={showForm?'':'collapsed'}/></button>{showForm&&<><div className="proposal-intro"><p>What are you considering for this parcel?</p>{tab==='compare'&&<div className="scenario-selector">{(['A','B'] as const).map(s=><button className={active===s?'selected':''} key={s} onClick={()=>setActive(s)}>Scenario {s}</button>)}<button aria-label="Copy scenario A to B" title="Copy A to B" onClick={()=>{setB({...a});setActive('B');setDirty(true);}}><Copy size={16}/></button></div>}</div><form onSubmit={e=>{e.preventDefault();void run(result?.parcel.pin??pin,tab==='compare'?'compare':'report');}}><fieldset disabled={busy}><ProposalForm proposal={active==='A'?a:b} onChange={change}/></fieldset><p className="input-note"><Info size={14}/>Height and footprint are context only; their placement and compliance are not assessed.</p><button className="primary-button" type="submit" disabled={busy}>{busy?<><LoaderCircle size={17} className="spin"/>Checking public sources…</>:<>{tab==='compare'?'Compare proposals':'Analyze proposal'}<ArrowRight size={17}/></>}</button></form></>}</section>}
 {dirty&&tab!=='sources'&&<p className="stale-note" role="status">Proposal changed. {tab==='compare'?'Compare':'Analyze'} again to update the results below.</p>}
 {tab==='report'&&display&&<><section className="results-card"><div className="section-heading"><div className="heading-with-step"><span className="step-number">02</span><h2>Your screening</h2></div><span className="tiny-label">SCENARIO A</span></div><Score result={display}/><details className="deductions"><summary>How this score is calculated <ChevronDown size={14}/></summary><p>SCORING_V1 starts at 100. Concern −5; major concern −15; apparent conflict −25. A zoning conflict caps the result at 49. These weights are provisional, not empirically calibrated.</p>{display.score.deductions.map(d=><button key={d.findingId} onClick={()=>setEvidence(display.findings.find(f=>f.id===d.findingId)!)}>{display.findings.find(f=>f.id===d.findingId)?.title}<strong>−{d.points}</strong></button>)}{!display.score.deductions.length&&<p>No identified deductions. Unassessed checks are not passes.</p>}{display.score.capApplied&&<p>Apparent zoning conflict: final score capped at 49.</p>}{display.score.criticalUnknownIds.length>0&&<p>Score withheld: {display.score.criticalUnknownIds.join(', ')}.</p>}</details></section>
 <section className="findings-section"><div className="section-heading"><h2>What the evidence says</h2><span>{display.findings.length} checks</span></div>{(['regulatory','physical'] as const).map(group=><div key={group}><h3 className="group-label">{group==='regulatory'?'REGULATORY':'PHYSICAL SITE'}</h3>{display.findings.filter(f=>f.category===group).map(f=><button className="finding-card" key={f.id} onClick={()=>setEvidence(f)}><span className={`finding-icon ${f.status}`}>{f.status==='pass'?<Check size={17}/>:f.status==='unknown'?<Info size={17}/>:<Flag size={17}/>}</span><span className="finding-body"><span className="finding-title">{f.title}<span className={`badge ${f.status}`}>{labels[f.status]}</span></span><span className="finding-summary">{f.summary}</span></span><ChevronRight size={16}/></button>)}</div>)}</section><section className="next-steps"><div className="section-heading"><h2>Verify next</h2><Flag size={18}/></div>{[...issues].sort((x,y)=>y.penalty-x.penalty).slice(0,3).map((f,i)=><div key={f.id}><span>{i+1}</span><p>{f.nextStep}<button onClick={()=>setEvidence(f)}>View evidence <ArrowUpRight size={12}/></button></p></div>)}</section></>}
 {tab==='compare'&&<section className="comparison-panel">{comparison?<><div className="section-heading"><h2>What changes?</h2><span className="badge neutral">Same parcel & source snapshot</span></div><div className="score-pair"><Score result={comparison.a} name="SCENARIO A"/><Score result={comparison.b} name="SCENARIO B"/></div><div className="change-highlight">{comparison.scoreDifference===null?'Scores are not comparable with the current check coverage.':`${comparison.scoreDifference>0?'+':''}${comparison.scoreDifference} points from A to B`}<p>Changed inputs: {comparison.changedFields.map(f=>fieldNames[f]).join(', ')||'None'}.</p></div>{comparison.changes.length===0?<p>No implemented finding changed. Stories, height and footprint area do not drive a scored rule.</p>:comparison.changes.map(c=><article className="change-row" key={c.findingId}><h3>{c.title}</h3><p><span className={`badge ${c.beforeStatus}`}>{labels[c.beforeStatus]}</span> → <span className={`badge ${c.afterStatus}`}>{labels[c.afterStatus]}</span></p><p>{c.explanation}</p><small>Caused by {c.reasonFields.map(f=>fieldNames[f]).join(', ')}.</small><p>{c.nextStep}</p><button className="text-link" onClick={()=>{setActive('B');setEvidence(comparison.b.findings.find(f=>f.id===c.findingId)!);}}>Review evidence <ArrowUpRight size={14}/></button></article>)}<div className="unchanged"><Check size={18}/><div><strong>{comparison.unchangedFindingIds.length} findings stayed the same</strong><p>{comparison.a.findings.filter(f=>comparison.unchangedFindingIds.includes(f.id)).map(f=>f.title).join(' · ')}</p><p>Changing a proposal does not change parcel-level hazards.</p></div></div></>:<div className="empty-state"><Copy size={32}/><h2>One site. Two possibilities.</h2><p>Adjust Scenario B above, then compare both proposals against the same public-data snapshot.</p></div>}</section>}
 {tab==='sources'&&result&&<section className="sources-panel"><div className="eyebrow">TRACEABLE BY DESIGN</div><h2>Public records, visible limits.</h2><p>Every finding links to its source. Retrieval dates describe when data was accessed, not when ground conditions were last surveyed.</p>{result.sources.map(s=><SourceLink key={s.id} source={s}/>)}<h3>Rules & scoring</h3><p>{result.rulesetVersion} · {result.score.scoringVersion}</p><p>Public snapshots and cached responses retain their original retrieval dates. The core report uses deterministic rules and templates, with no AI API required.</p></section>}
 {result&&tab!=='sources'&&<section className="financial-card"><div><FileText size={20}/><h3>Financial feasibility</h3><span className="badge neutral">Not assessed</span></div><p>Acquisition price, hard and soft costs, expected sale or rent, financing, and subsidies need a separate review.</p><details><summary>Other checks not assessed</summary><p>{result.unassessedCheckIds.filter(id=>id!=='finance').map(id=>id.replace(/^(site|zoning)\./,'').replaceAll('_',' ')).join(' · ')}</p></details></section>}
 {result?.warnings.map(w=><p key={w} className="warning-note"><Info size={16}/>{w}</p>)}
 </div></div><footer><ShieldCheck size={18}/><p><strong>Preliminary screening.</strong> Verify zoning interpretation and site conditions with the City and qualified professionals.</p><span>ParcelPilot · Pittsburgh</span></footer></main>{evidence&&display&&<Evidence finding={evidence} sources={display.sources} onClose={()=>setEvidence(null)}/>}</>;
}
